spring:
  datasource:
   # driver-class-name: com.microsoft.sqlserver.jdbc.SQLServerDriver
    driver-class-name: org.h2.Driver
  #  url: jdbc:sqlserver://localhost:1433;DatabaseName=test;user=sa;password=c0re!0t123;trustServerCertificate=true
  application:
    name: inventory-service
  config:
    import: "optional:configserver:http://localhost:8096"
  jpa:
    show-sql: true
    properties:
      hibernate:
        format_sql: true
        show_sql: true
        use_sql_comments: true
  h2:
    console:
      enabled: true
    datasource:
      initialization-mode: always
      driverClassName: org.h2.Driver
      jdbcUrl: dbc:h2:file:./db/inventoryServiceDB
      username: c0mplex
      password: c0mplexP@ssw0rd!123
